export const SET_PROFILE_STATS = "SET_PROFILE_STATS"
export const FETCH_PROFILE_START = "FETCH_PROFILE_START"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL"

export const FETCH_USER_RECIPES_START = "FETCH_USER_RECIPES_START"
export const FETCH_USER_RECIPES_SUCCESS = "FETCH_USER_RECIPES_SUCCESS"
export const FETCH_USER_RECIPES_FAIL = "FETCH_USER_RECIPES_FAIL"

export const USER_AUTH_START = "USER_AUTH_START"
export const USER_AUTH_FAIL = "USER_AUTH_FAIL"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const LOGOUT = "LOGOUT"