export const SET_PROFILE_STATS = "SET_PROFILE_STATS"
export const FETCH_PROFILE_START = "FETCH_PROFILE_START"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL"