export const FETCH_USER_RECIPES_START = "FETCH_USER_RECIPES_START"
export const FETCH_USER_RECIPES_SUCCESS = "FETCH_USER_RECIPES_SUCCESS"
export const FETCH_USER_RECIPES_FAIL = "FETCH_USER_RECIPES_FAIL"